export const routes = {
  BOTTOM_TAB: 'BOTTOM_TAB',
  HOME_SCREEN: 'HOME_SCREEN',
  NOTIFICATION_SCREEN: 'NOTIFICATION_SCREEN',
  PROFILE_SCREEN: 'PROFILE_SCREEN',
  NEWS_DETAILS: 'NEWS_DETAILS',
  PROMOTION_DETAILS: 'PROMOTION_DETAILS',
  DETAILS_NOTIFICATION: 'DETAILS_NOTIFICATION',
  LOGIN_SCREEN: 'LOGIN_SCREEN',
  SIGNUP_SCREEN: 'SIGNUP_SCREEN',
};
